src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ParticipantRepository::class)
 * @UniqueEntity(fields={"mail"}, message="There is already an account with this email")
 */
class Participant implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="text")
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $administrateur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;


    /**
     * @ORM\ManyToMany(targetEntity=Sortie::class, inversedBy="inscrit")
     */
    private $inscrit;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="organisateur")
     */
    private $sorties;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    public function __construct()
    {
        $this->inscrit = new ArrayCollection();
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->mail;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->roles;

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isAdministrateur(): ?bool
    {
        return $this->administrateur;
    }

    public function setAdministrateur(bool $administrateur): self
    {
        $this->administrateur = $administrateur;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCampus(): ?campus
    {
        return $this->campus;
    }

    public function setCampus(?campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getInscrit(): Collection
    {
        return $this->inscrit;
    }

    public function addInscrit(Sortie $inscrit): self
    {
        if (!$this->inscrit->contains($inscrit)) {
            $this->inscrit[] = $inscrit;
        }

        return $this;
    }

    public function removeInscrit(Sortie $inscrit): self
    {
        $this->inscrit->removeElement($inscrit);

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getOrganisateur() === $this) {
                $sorty->setOrganisateur(null);
            }
        }

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Etat;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\Ville;
use App\Repository\LieuRepository;
use App\Repository\VilleRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class SortieType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('nom')
            ->add('dateHeureDebut', DateType::class)
            ->add('dateLimiteInscription')
            ->add('duree')
            ->add('nbInscriptionsMax', IntegerType::class)
            ->add('infosSortie')
            ->add('campus', EntityType::class,['class'=>Campus::class,'mapped' => false,'choice_label'=>'nom'])
            ->add('ville', EntityType::class,
                [
                    'class'=>Ville::class,
                    'mapped' => false,
                    'query_builder' => function(VilleRepository $villeRepository ){ return $villeRepository->createQueryBuilder('c')->orderBy('c.nom');}
                ]
            )
            ->add('lieu' , EntityType::class,['class'=>Lieu::class,'choice_label'=>'nom' ])
            ->add('etat', EntityType::class,['class' => Etat::class,'choice_label'=>'libelle']);

    }



    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }


}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Campus;
use App\Entity\Etat;
use App\Entity\Lieu;
use App\Entity\Participant;
use App\Entity\Sortie;
use App\Entity\Ville;
use App\Form\SearchSortieType;
use App\Form\SortieType;
use App\Repository\LieuRepository;
use App\Repository\ParticipantRepository;
use App\Repository\SortieRepository;
use App\Repository\VilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/sortie")
 */
class SortieController extends AbstractController
{
    /**
     * @Route("/", name="app_sortie_index")
     */
    public function index(Request $request, SortieRepository $sortieRepository): Response
    {
        $user = $this->getUser();
        #fsvdfsd
        $data = new Sortie();
        $form = $this->createForm(SearchSortieType::class, $data);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            #return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);

            $campus=$request->get('campus');
            $nom= '%' . $request->get('nom') . '%';
            $dateDebut= $request->get('dateDebut');
            $dateFin= $request->get('dateFin');
            $idUser = $user->getUserIdentifier();
            $sortieOrga = $request->get('orga');;
            $sortieInscrit = $request->get('inscrit');;
            $sortiePasInscrit = $request->get('pasInscrit');;
            $sortiePasse = $request->get('passer');;

            $sorties = $sortieRepository->search($campus, $nom, $dateDebut, $dateFin, $idUser, $sortieOrga, $sortieInscrit, $sortiePasInscrit, $sortiePasse);
        }
        else
        {
            $sorties = $sortieRepository->findAll();
        }

        return $this->render('sortie/index.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'sorties' => $sorties,
        ]);
    }

    /**
     * @Route("/new", name="app_sortie_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SortieRepository $sortieRepository, ParticipantRepository $participantRepository, LieuRepository $lieuRepository): Response
    {
        $sortie = new Sortie();
        $lieu = $lieuRepository->findAll();

        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);

        $sortie->setOrganisateur($participantRepository->find(9)); //--------------------------------------------------------------------------------------------------------------- ICI
        $sortie->setSiteOrganisateur($participantRepository->find(9)->getCampus());

        if ($form->isSubmitted() && $form->isValid()) {
            $sortieRepository->add($sortie, true);
            return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sortie/new.html.twig', [
            'sortie' => $sortie,
            'lieu' => $lieu,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/id/{id}", name="app_sortie_show", methods={"GET"})
     */
    public function show(Sortie $sortie): Response
    {
        $user = $this->getUser();
        $today = date("Y-m-d");

        $inscrits = $sortie->getInscrit()->toArray();
        $BoolInscrit = false;
        foreach ($inscrits as $inscrit)
        {
            if ($inscrit->getId() == $user->getUserIdentifier())
            {
                $BoolInscrit = true;
            }
        }
        return $this->render('sortie/show.html.twig', [
            'sortie' => $sortie,
            'user' => $user,
            'today' => $today,
            'inscrit' => $BoolInscrit,
        ]);
    }

    /**
     * @Route("/id/{id}/edit", name="app_sortie_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Sortie $sortie, SortieRepository $sortieRepository): Response
    {
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sortieRepository->add($sortie, true);

            return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sortie/edit.html.twig', [
            'sortie' => $sortie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_sortie_delete")
     */
    public function delete(Request $request, Sortie $sortie, SortieRepository $sortieRepository, EntityManagerInterface $entityManager): Response
    {
        $sortieRepository->remove($sortie, true);

        return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/search", name="sortie_listeSearch")
     * @param EntityManagerInterface $entityManager
     * @param $query
     * @return Response
     */
    public function listeSearch(EntityManagerInterface $entityManager, $query)
    {
        $idUser = 1;
        $sortieOrga = false;
        $sortieInscrit = false;
        $sortiePasInscrit = false;
        $sortiePasse = false;


        if ($sortieOrga)
        {
            $query->andWhere('s.organisateur = :id')->setParameter('id', $idUser);
        }

        if ($sortieInscrit)
        {
            $query->innerJoin('s.inscrit', 'p');
            $query->andWhere('p.id = :id') ->setParameter('id', $idUser);
        }

        if ($sortiePasInscrit)
        {
            $query->innerJoin('s.inscrit', 'p');
            $query->andWhere('p.id != :id')->setParameter('id', $idUser);
        }

        if ($sortiePasse)
        {
            $query->andWhere('s.etat = 2 ');
        }

        $query = $query->getQuery();
        $sorties = $query->getResult();


        return $this->render('sortie/accueil.html.twig', [
            'sorties' => $sorties
        ]);
    }

    /**
     * @Route ("/inscription/{id}", name="sortie_inscription")
     */
    public function inscription(Sortie $sortie, ParticipantRepository $participantRepository, EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();

        $sortie->addInscrit($participantRepository->find($user->getUserIdentifier()));
        $entityManager->persist($sortie);
        $entityManager->flush();

        return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route ("/deinscription/{id}", name="sortie_deinscription")
     */
    public function deinscription(Sortie $sortie, ParticipantRepository $participantRepository, EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();

        $sortie->removeInscrit($participantRepository->find($user->getUserIdentifier()));
        $entityManager->persist($sortie);
        $entityManager->flush();

        return $this->redirectToRoute('app_sortie_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/sortie/_SearchForm.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

<label for="dateDebut">Date Début</label>
<input type="date" id="dateDebut" name="dateDebut"  min="2020-01-01" max="2030-01-01">

<label for="dateFin">Date Fin</label>
<input type="date" id="dateFin" name="dateFin"  min="2020-01-01" max="2030-01-01">

<fieldset>
    <legend></legend>

    <div>
        <label for="orga">Sorties dont je suis l'organisateur/trice</label>
        <input type="checkbox" id="orga" name="orga">
    </div>

    <div>
        <label for="inscrit">Sorties auxquelles je suis inscrit/e</label>
        <input type="checkbox" id="inscrit" name="inscrit">
    </div>

    <div>
        <label for="pasInscrit">Sorties auxquelles je ne suis pas inscrit/e</label>
        <input type="checkbox" id="pasInscrit" name="pasInscrit">
    </div>

    <div>
        <label for="passer">Sorties passées</label>
        <input type="checkbox" id="passer" name="passer">
    </div>

</fieldset>

<button class="btn">{{ button_label|default('Rechercher') }}</button>

{{ form_end(form) }}

templates/sortie/_delete_form.html.twig
<form method="post" action="{{ path('app_sortie_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sortie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/sortie/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} | Accueil
{% endblock %}

{% block body %}
    <h1>Accueil</h1>

    <table>
        {% for sortie in sorties %}
            <tr>
                <td>{{ sortie.nom }}</td>
                <td>{{ sortie.dateHeureDebut.format('d-m-Y') }}</td>
                <td>{{ sortie.dateLimiteInscription.format('d-m-Y') }}</td>
                <td>countParticipant / {{ sortie.nbInscriptionsMax }}</td>
                <td>{{ sortie.etat.libelle }}</td>
                <td>Inscrit</td>
                <td>{{ sortie.organisateur.nom }}</td>
                <td>Action</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sortie{% endblock %}

{% block body %}
    <h1>Edit Sortie</h1>

    {{ include('sortie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_sortie_index') }}">back to list</a>

    {{ include('sortie/_delete_form.html.twig') }}
{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie index{% endblock %}

{% block user %}
    <p>{{ user.username }}</p>
{% endblock %}



{% block body %}
    <h1>Sortie index</h1>

    {{ include('sortie/_SearchForm.html.twig', {'button_label': 'Rechercher'}) }}

    <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Date Debut</th>
            <th>Duree</th>
            <th>Date Limite Inscription</th>
            <th>Inscriptions</th>
            <th>InfosSortie</th>
            <th>Organisateur</th>
            <th>Etat</th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
        {% for sortie in sorties %}
            <tr>
                <td>{{ sortie.nom }}</td>
                <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('Y-m-d') : '' }}</td>
                <td>{{ sortie.duree ? sortie.duree|date('H:i') : '' }}</td>
                <td>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('Y-m-d') : '' }}</td>
                <td> {{ sortie.inscrit.count}} / {{ sortie.nbInscriptionsMax }}</td>
                <td>{{ sortie.infosSortie }}</td>
                <td>{{ sortie.organisateur.nom }}</td>
                <td>{{ sortie.etat.libelle }}</td>
                <td>
                    <a href="{{ path('app_sortie_show', {'id': sortie.id}) }}">show</a>
                    {% if sortie.organisateur.id == user.userIdentifier  or user.roles[0]  == "ROLE_ADMIN" %}
                        <a href="{{ path('app_sortie_edit', {'id': sortie.id}) }}">edit</a>
                        <a href="{{ path('app_sortie_delete', {'id': sortie.id}) }}">delete </a>
                    {% endif %}

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lieu_new') }}">Create new</a>
{% endblock %}

templates/sortie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Sortie{% endblock %}

{% block body %}
    <h1>Create new Sortie</h1>

    {{ include('sortie/_form.html.twig') }}

    <a href="{{ path('app_sortie_index') }}">back to list</a>
{% endblock %}

templates/sortie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie{% endblock %}

{% block user %}
    <p>{{ user.username }}</p>
{% endblock %}

{% block body %}
    <h1>Sortie</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ sortie.id }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ sortie.nom }}</td>
        </tr>
        <tr>
            <th>DateHeureDebut</th>
            <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Duree</th>
            <td>{{ sortie.duree ? sortie.duree|date('H:i') : '' }}</td>
        </tr>
        <tr>
            <th>DateLimiteInscription</th>
            <td>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>NbInscriptions</th>
            <td>{{ sortie.inscrit.count }} / {{ sortie.nbInscriptionsMax }}</td>
        </tr>
        <tr>
            <th>InfosSortie</th>
            <td>{{ sortie.infosSortie }}</td>
        </tr>
        <tr>
            <th>Etat</th>
            <td>{{ sortie.etat.libelle }}</td>
        </tr>
        </tbody>
    </table>
    {% if today < sortie.dateLimiteInscription|date('Y-m-d') and sortie.inscrit.count < sortie.nbInscriptionsMax and inscrit == false %}
        <a href="{{ path('sortie_inscription',{'id': sortie.id}) }}">Inscription</a>
    {% endif %}

    {% if inscrit == true %}
        <a href="{{ path('sortie_deinscription',{'id': sortie.id}) }}">Désinscription</a>
    {% endif %}

    {% if sortie.organisateur.id == user.userIdentifier  or user.roles[0]  == "ROLE_ADMIN" %}
        <a href="{{ path('app_sortie_edit', {'id': sortie.id}) }}">edit</a>
        {{ include('sortie/_delete_form.html.twig') }}
    {% endif %}

    <a href="{{ path('app_sortie_index') }}">back to list</a>

{% endblock %}